sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: uhOUlThNuR9onZlXtU2PnSNY1qpYhBgytGMPc2aq1WSSeeV6X3nd0XtAly4FZ8V4ObXtkeHyQJ+nTSVzVh+2fqjoI5dZUB3ApNMykJS1vBWlAvlv1vt6x6yIG4lNCvegOf3G9NgqAcSwVy+8v481nDbHex3qnXwDinSJjoEe0+kYnLqoR+2yQkzo4SfXgTHzDAAUP4Dv07X9asKVSVdVpF5viz6nrZk6rJilW3uL1JmdalajRtVIt4GxF44MJ4iALvIincEBCQ2E4+ogATzICzdtzua8rwlzzcQL/9JLBdvuJ7TpgVhEs7yCkMh/WvsfkjW5+Rc6vtUU6JyF2V22AxNatFQCPjC2esCIUCyD14zpY0dPkVl0p/QSlteXojDHjRmGD8PQSvjqg8Ohxt6rAkZBmXM8zm2jLtbJZRVkDWh4RFo2Efd077+pHIdMZHWuJKkL8EVdUWDltWX+Spz8qrS30VO9AbolFvZvZ97N5M6M8Kzdm8Qblktk+ml5WbrRNvXmEteuAjPIbLQfuqwXFobWe+M281CmRFatH53BBN5TdXX3k1oKbc/LIrOMM+hf4sxaLZLeCXom0rA7q4/W1Z71LNUsp1Ghdkfl4rUPCwDbJEy78wXuwwS27Q7RqSrANPQ7TiOJAydT6VeN3/h7TNymWDXKteeYMvL8qYMSHas=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-History-of-Don-Quixote-Volume-2-Part-23_5926
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy